#!/bin/bash

repo="$(git rev-parse --show-toplevel)" || exit
cd "$repo" || exit

node test/exports.js || exit

node test/cat.js || exit
node test/cat-better.js || exit

node test/echo.js || exit

node test/overflow-in.js || exit
node test/overflow-out.js || exit

#node test/enoent.js || exit
